### ISSUE TITLE
Cannot merge and transform

### ISSUE THREAD

**Issue by jcvillegas77** [syJSdev/rollup-plugin-copy-merge#14]
Hello,

If I try to merge with multiple src files, file and transform, I'm getting the following error:
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2123:5)

Looking over the code I think I found a bug at this line:
https://github.com/syJSdev/rollup-plugin-copy-merge/blob/b9d3e87afd368896c1c603973caced06e3552c8e/src/index.js#L171

It should be:
` if (contents)  await fs.outputFile(dest, contents);`

I tested this directly editing the source file in node_modules and it worked. I know this is not the way to do it, but I have zero knowledge github and pull requests.

I appreciate your help!

**Comment by syJSdev** [comment]
I released a patched version. please check [v1.0.2](https://www.npmjs.com/package/rollup-plugin-copy-merge/v/1.0.2)
