### ISSUE TITLE
Rollup plugin Copy merge plugin doesn't merge files but instead overwrites the file

### ISSUE THREAD

**Issue by kukrejashikha02** [syJSdev/rollup-plugin-copy-merge#5]
I'm using the latest version 0.2.0 and i've noticed that this plugin overwrites the existing file with the src file passed to it. This is what I'm doing 

 copy({
            targets: [
                {
                    src:
                        './src/components/data/DataTable/types/react-table/index.d.ts',
                    file: './dist/index.d.ts'
                }
            ]
        })

It overwrites the index.d.ts file generated by the typescript compiler with this file (src/components/data/DataTable/types/react-table/index.d.ts)

**Comment by syJSdev** [comment]
That's the expected result.
So, If you don't want to overwrite the `./dist/index.d.ts`, don't use this file location in `file` attribute.

Note: Please let me know what you want to try.

**Comment by syJSdev** [comment]
So closing... if you think this is actually a bug then reopen it.

**Comment by syJSdev** [comment]
found a tricky solution.

```js
copy({
  targets: [
    {
      src: ['dest-file', ...],
      file: 'dest-file'
    }
  ]
});
```

In your case
```js
copy({
  targets: [
    {
      src: ["./dist/index.d.ts", "./src/components/data/DataTable/types/react-table/index.d.ts"],
      file: "./dist/index.d.ts",
    },
  ],
});
```

Let me know if this works for you.
