### ISSUE TITLE
postinstall script breaks projects

### ISSUE THREAD

**Issue by rchl** [syJSdev/rollup-plugin-copy-merge#7]
This postinstall script also tries to run when installing this dependency in a parent project:

https://github.com/syJSdev/rollup-plugin-copy-merge/blob/bb66b9464b4ecfa0339f68496a6ea666d500ba02/package.json#L19

It breaks npm install since those packages are not necessarily installed in the parent project. I think it might work to use `prepare` hook instead.

**Comment by syJSdev** [comment]
Hi @rchl ,
> Yarn 2+ doesn't support prepare lifecycle script, so husky needs to be installed differently (this doesn't apply to Yarn 1 though). See [Yarn 2+ install](https://typicode.github.io/husky/#/?id=yarn-2).

It seems husky updated their documentation for the yarn 2.
Thanks for the bug report and will fix it soon.
